"""add workouts table

Revision ID: 986c99f46644
Revises: 171c15af49a4
Create Date: 2026-04-01 10:07:48.627649
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision: str = '986c99f46644'
down_revision: Union[str, None] = '171c15af49a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_user_id'), 'workouts', ['user_id'], unique=False)
    op.add_column('workout_entries', sa.Column('workout_id', sa.Integer(), nullable=False))
    op.drop_index('ix_workout_entries_user_id', table_name='workout_entries')
    op.create_index(op.f('ix_workout_entries_workout_id'), 'workout_entries', ['workout_id'], unique=False)
    op.drop_constraint('workout_entries_user_id_fkey', 'workout_entries', type_='foreignkey')
    op.create_foreign_key(None, 'workout_entries', 'workouts', ['workout_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workout_entries', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_entries', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workout_entries', type_='foreignkey')
    op.create_foreign_key('workout_entries_user_id_fkey', 'workout_entries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_workout_entries_workout_id'), table_name='workout_entries')
    op.create_index('ix_workout_entries_user_id', 'workout_entries', ['user_id'], unique=False)
    op.drop_column('workout_entries', 'workout_id')
    op.drop_index(op.f('ix_workouts_user_id'), table_name='workouts')
    op.drop_table('workouts')
    # ### end Alembic commands ###